language: php

services:
  - mysql

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database cosst;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  - php artisan key:generate
  - php artisan migrate
